//CAMPAIGN ACTIONS
export let ADD_CAMPAIGN = "ADD_CAMPAIGN";
export let SET_ACTIVE_CAMPAIGNS = "SET_ACTIVE_CAMPAIGNS";
export let SET_INACTIVE_CAMPAIGNS = "SET_INACTIVE_CAMPAIGNS";
export let SET_ARCHIVED_CAMPAIGNS = "SET_ARCHIVED_CAMPAIGNS";
export let CAMPAIGN_GRID_VIEW = "CAMPAIGN_GRID_VIEW";
export let CAMPAIGN_LIST_VIEW = "CAMPAIGN_LIST_VIEW";
export let SEARCH_CAMPAIGN = "SEARCH_CAMPAIGN";
export let SET_ENABLE_CAMPAIGN = "SET_ENABLE_CAMPAIGN";
export let SET_DISABLE_CAMPAIGN = "SET_DISABLE_CAMPAIGN";
export let SET_CHECK_CAMPAIGN = "SET_CHECK_CAMPAIGN";
export let SET_UNCHECK_CAMPAIGN = "SET_UNCHECK_CAMPAIGN";
export let SET_CAMPAIGN_STATUS = "SET_CAMPAIGN_STATUS";
export let SET_CAMPAIGN_SAVE_AS_DRAFT = "SET_CAMPAIGN_SAVE_AS_DRAFT";
export let CAMPAIGN_SKIP_PROMOTION = "CAMPAIGN_SKIP_PROMOTION";
export let CAMPAIGN_ADD_PROMOTIONS = "CAMPAIGN_ADD_PROMOTIONS";
export let CAMPAIGN_SKIP_SURVEY = "SKIP_SURVEY";
export let CAMPAIGN_ADD_SURVEY = "CAMPAIGN_ADD_SURVEY";
export let CAMPAIGN_SAVE_CHANGES = "CAMPAIGN_SAVE_CHANGES";
export let CANCEL_CAMPAIGN = "CANCEL_CAMPAIGN";


//PROMOTION ACTIONS
export let ADD_PROMOTION = "ADD_PROMOTION";
export let SET_ACTIVE_PROMOTIONS = "SET_ACTIVE_PROMOTIONS";
export let SET_INACTIVE_PROMOTIONS = "SET_INACTIVE_PROMOTIONS";
export let SET_ARCHIVED_PROMOTIONS = "SET_ARCHIVED_PROMOTIONS";
export let PROMOTION_GRID_VIEW = "PROMOTION_GRID_VIEW";
export let PROMOTION_LIST_VIEW = "PROMOTION_LIST_VIEW";
export let SEARCH_PROMOTION = "SEARCH_PROMOTION";
export let SET_ENABLE_PROMOTION = "SET_ENABLE_PROMOTION";
export let SET_DISABLE_PROMOTION = "SET_DISABLE_PROMOTION";
export let SET_CHECK_PROMOTION = "SET_CHECK_PROMOTION";
export let SET_UNCHECK_PROMOTION = "SET_UNCHECK_PROMOTION";
export let SET_PROMOTION_STATUS = "SET_PROMOTION_STATUS";
export let SET_PROMOTION_SAVE_AS_DRAFT = "SET_PROMOTION_SAVE_AS_DRAFT";
export let PROMOTION_SELECT_CAMPAIGN = "PROMOTION_SELECT_CAMPAIGN";
export let PROMOTION_ADD_MORE_CAMPAIGN = "PROMOTION_ADD_MORE_CAMPAIGN";
export let PROMOTION_SKIP_SURVEY = "PROMOTION_SKIP_SURVEY";
export let PROMOTION_ADD_MORE_SURVEY = "PROMOTION_ADD_MORE_SURVEY";
export let PROMOTION_SAVE_CHANGES = "PROMOTION_SAVE_CHANGES";
export let CANCEL_PROMOTION = "CANCEL_PROMOTION";